# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHotel', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('imageSource', models.CharField(max_length=200)),
                ('webSource', models.CharField(max_length=200)),
                ('numComentarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
    ]
