# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0003_auto_20160619_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='imageUrl',
            new_name='imageUrls',
        ),
        migrations.AddField(
            model_name='hotel',
            name='imageNum',
            field=models.IntegerField(default=0),
        ),
    ]
