# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0005_auto_20160623_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='css',
            old_name='marcos',
            new_name='colormarcos',
        ),
        migrations.RenameField(
            model_name='css',
            old_name='titulo',
            new_name='grosormarcos',
        ),
        migrations.AddField(
            model_name='css',
            name='tamanioletra',
            field=models.CharField(default='', max_length=200),
        ),
    ]
