# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0008_auto_20160625_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='hotel',
        ),
        migrations.AddField(
            model_name='comentario',
            name='idhotel',
            field=models.CharField(default='', max_length=200),
        ),
    ]
