# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0009_auto_20160625_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoteles.Hotel')),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
