# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoteles', '0010_auto_20160625_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='firstFoto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
